---
title       : Johns Hopkins Data Products Class Presentation (algebraVIS)
subtitle    : Learning Algebra for the Uninitiated Adult
author      : Cynthia Davies Cunha
job         : Data Scientist (student)
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax, quiz, bootstrap]     # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Background Information

. This project is an **initial** effort to design a teaching program for an Uninitiated Adult Learner.

    - A very long time ago my father asked that I teach him Algebra
    
    - I failed at that effort.
    
    - Here I begin again with another, perhaps two(?), Adult Learners.
    
. The subject is Algebra

. We begin with the concept of *Containers*.

    - Sometimes a letter is not a letter.
    
    - Sometimes it is a Container.
    
    
---  

## Ultimate Plan of Attack (...initial thinking...)

1.  Introducing a Container

2.  Solving problems with one Container (unknown variable)*

3.  Solving problems with two Containers* 

4.  Word Problems: essential skills*

*not covered in this version


Recognizing the meaning of the following type of equation is step one in our journey:

$$ x + 3 = 7 $$
$$ ? + 3 = 7 $$
$$ a - 3 = 4 $$

---

## Well, what is a Container?


. A **Container** is a representation of an *unknown value*.

    - This concept can be difficult to grasp for the uninitiated
    
    - When is a letter not a letter? 
    
    - Answer: when it is a representation for an *unknown value.*
 
 
. To recap:    
    - Lesson one: What is a Container.  
    - Objective: To be able to answer this primary question.  
    - Reinforcement: User-created equations with different containers represented (and an example of each solved).

--- &radio

## Question 1

What is a Container?

1.  A numerical representation.
2. _It is a representation of an unknown value._
3.  Something the cat dragged in.
4.  It is designed to put something in.

*** .hint
Review the first lesson again.  It is important to master this concept.

*** .explanation
In Algebra, we typically represent unknown values with a letter designation, like 'x' or 'y'.

---

## Recognizing Containers

Can you answer the following container questions now?  

What is the value of the container **x** in the following? $$ x + 4 = 7 $$ 
answer: $3$

What is the container in $$ 2x + 3 = 0 $$
answer: x

What is the value of the container **a** in the following?$$ a + 1 = 3 $$
answer: $2$
